### ISSUE TITLE
https://www.justlovesmile.top

### ISSUE THREAD

**Issue by Justlovesmile** [Justlovesmile/friend-issue#1]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: MJ的个人主页

# 跳转地址
link: https://www.justlovesmile.top

# 你的头像
avatar: https://npm.elemecdn.com/justlovesmile-static/img/avatar.jpg

# 你的描述
descr: 醒亦念卿，梦亦念卿

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: https://cdn.jsdelivr.net/gh/Justlovesmile/CDN2/post/202108251708466.png
```
