### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by zisheng-ai** [Justlovesmile/friend-issue#10]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: 洛竹的博客

# 跳转地址
link: https://youngjuning.js.org

# 你的头像
avatar: https://picbed.qunarzz.com/af8c84d2c24a6b971153e6620f3218ad.png

# 你的描述
descr: 真理无穷，一寸欢喜

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: 
```
