### ISSUE TITLE
https://wuster.store/

### ISSUE THREAD

**Issue by xiwuqi** [Justlovesmile/friend-issue#11]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: 梧席

# 跳转地址
link: https://wuster.store/

# 你的头像
avatar: https://wuster.store/images/me.JPG

# 你的描述
descr: 走在小径分岔的花园

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: 
```
