### ISSUE TITLE
https://www.kevinwu.cc/

### ISSUE THREAD

**Issue by kmeykranz** [Justlovesmile/friend-issue#12]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: 阿谦

# 跳转地址
link: https://www.kevinwu.cc/

# 你的头像
avatar: https://bed.kevinwu.cc/img/avatar.jpg

# 你的描述
descr: 你若安好，便是晴天

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: 
```
