### ISSUE TITLE
https://weizwz.com/

### ISSUE THREAD

**Issue by weizwz** [Justlovesmile/friend-issue#13]
```yaml
- name: 唯之为之
  link: https://weizwz.com
  avatar: https://weizwz.com/img/avatar/head.jpg
  siteshot: https://weizwz.com/img/avatar/siteshot.png
  descr: 时光笔墨
```
