### ISSUE TITLE
https://chxc.cc

### ISSUE THREAD

**Issue by EnderCHX** [Justlovesmile/friend-issue#14]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: CHX小站

# 跳转地址
link: https://chxc.cc

# 你的头像
avatar: https://chxc.cc/img/chx.png

# 你的描述
descr: CHX小站

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: https://img.chxc.cc/file/fdc4c42e0d42d57eeaa24.png
```
