### ISSUE TITLE
https://lzxjack.top/

### ISSUE THREAD

**Issue by lzxjack** [Justlovesmile/friend-issue#2]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: 飞鸟

# 跳转地址
link: https://lzxjack.top/

# 你的头像
avatar: https://jack-img.oss-cn-hangzhou.aliyuncs.com/img/20201204121004.jpg

# 你的描述
descr: 一只平凡的鸟罢了。

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: https://jack-img.oss-cn-hangzhou.aliyuncs.com/img/20210826130744.jpg
```
