### ISSUE TITLE
https://blog.justlovesmile.top

### ISSUE THREAD

**Issue by Justlovesmile** [Justlovesmile/friend-issue#3]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: MJ's Blog
descr: 醒亦念卿，梦亦念卿
link: https://blog.justlovesmile.top
avatar: https://npm.elemecdn.com/justlovesmile-img/logo.jpg

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: 
```
