### ISSUE TITLE
https://blog.kobal.cn/

### ISSUE THREAD

**Issue by kebuAAA** [Justlovesmile/friend-issue#4]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: 爱编程的小明

# 跳转地址
link: https://blog.kobal.cn/

# 你的头像
avatar: https://gcore.jsdelivr.net/gh/kebuAAA/Picloud@main/img/avatar.webp

# 你的描述
descr:不要温和地走进那个良夜 

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: 
```
