### ISSUE TITLE
https://ll.sc.cn

### ISSUE THREAD

**Issue by cajunlei** [Justlovesmile/friend-issue#6]
**标题请书写你的链接，不要写其他内容**
```yaml
# 显示名称
name: 雷雷屋头

# 跳转地址
link: https://ll.sc.cn

# 你的头像
avatar: https://ll.sc.cn/img/avatar.png

# 你的描述
descr: 爱生活，爱工作，爱折腾。

#------------------------------#
#       以下字段为选填字段       #

# 风格 可选项 item和card
card_style: card
# 自定义网站截图（当样式为card时可以自定义网站截图，防止api接口宕掉无法显示图）
screenshot: https://ll.sc.cn/img/siteshot.webp
```
