### ISSUE TITLE
友链

### ISSUE THREAD

**Issue by roydonGuo** [Justlovesmile/friend-issue#7]
```yaml
- name: roydon
  link: https://www.roydon.top
  avatar: https://gcore.jsdelivr.net/gh/roydonGuo/CDN/avatar/ganyu4.png
  descr: 如琉璃般飘落
  theme_color: pink
  siteshot: https://bu.dusays.com/2023/01/04/63b5663b9c22e.png
```
