### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by xiaoyaohanyue** [Justlovesmile/friend-issue#8]
```yaml
name: 妖の森
link: https://fjwr.xyz
avatar: https://cdn.fjwr.xyz/handsome/assets/img/header.jpg
descr: 一个划水摸鱼的博主
```
